set(_CATKIN_CURRENT_PACKAGE "practica2")
set(practica2_VERSION "0.1.0")
set(practica2_MAINTAINER "RoboticsLLLC <none@gmail.com>")
set(practica2_PACKAGE_FORMAT "2")
set(practica2_BUILD_DEPENDS "roscpp" "std_msgs" "roslint" "geometry_msgs" "kobuki_msgs")
set(practica2_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "geometry_msgs" "kobuki_msgs")
set(practica2_BUILDTOOL_DEPENDS "catkin")
set(practica2_BUILDTOOL_EXPORT_DEPENDS )
set(practica2_EXEC_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "kobuki_msgs")
set(practica2_RUN_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "kobuki_msgs")
set(practica2_TEST_DEPENDS )
set(practica2_DOC_DEPENDS )
set(practica2_URL_WEBSITE "https://github.com/camilo-0715/roboticsLLLC.git")
set(practica2_URL_BUGTRACKER "")
set(practica2_URL_REPOSITORY "")
set(practica2_DEPRECATED "")